### ISSUE TITLE
error: implicit instantiation of undefined template 'std::__1::hash<int>'

### ISSUE THREAD

**Issue by deNULL** [tdlib/telegram-bot-api#24]
Trying to build on Ubuntu 16 with clang++ (using the instructions from https://tdlib.github.io/telegram-bot-api/build.html?os=Linux):

```
[ 58%] Building CXX object td/CMakeFiles/tdcore.dir/td/telegram/DialogAction.cpp.o
In file included from /root/telegram-bot-api/td/td/telegram/DialogAction.cpp:7:
In file included from /root/telegram-bot-api/td/td/telegram/DialogAction.h:9:
/root/telegram-bot-api/td/td/telegram/MessageContentType.h:75:12: error: implicit instantiation of undefined template 'std::__1::hash<int>'
    return std::hash<int32>()(static_cast<int32>(content_type));
           ^
/usr/include/c++/v1/memory:3150:29: note: template is declared here
template <class _Tp> struct hash;
                            ^
1 error generated.
td/CMakeFiles/tdcore.dir/build.make:974: recipe for target 'td/CMakeFiles/tdcore.dir/td/telegram/DialogAction.cpp.o' failed
make[2]: *** [td/CMakeFiles/tdcore.dir/td/telegram/DialogAction.cpp.o] Error 1
CMakeFiles/Makefile2:351: recipe for target 'td/CMakeFiles/tdcore.dir/all' failed
make[1]: *** [td/CMakeFiles/tdcore.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

Probably related to a recent [commit](https://github.com/tdlib/td/commit/645052bec7d984ea5fba5fc56150f06bfc566ddb) in tdlib/td repository.

**Comment by levlam** [comment]
Thanks! Fixed in master.

**Comment by deNULL** [comment]
It seems that you've changed the wrong file: the error is in `MessageContentType.h` and your fix changes `MessageContent.h`. Build error still persists, but it goes away after adding `#include <functional>` to `MessageContentType.h` (I'm too lazy for a proper pull request though).

**Comment by levlam** [comment]
Yes, you are right. I pushed the correct fix.
